
workflows:
  ios-workflow:
    name: Intake on-the-Go iOS
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_CONNECT_ISSUER_ID: "2cc1b994-49d1-4b7a-9d18-767f2f0d947f"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "3FQWFK9UTA"
    scripts:
      - name: Unzip project
        script: |
          unzip "Intake on-the-Go.zip"
      - name: Install CocoaPods
        script: |
          cd src
          pod install
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files \
            org.aohministry.intakeonthego \
            --type IOS_APP_STORE \
            --create
      - name: Set up keychain
        script: keychain initialize
      - name: Add certificate to keychain
        script: keychain add-certificates
      - name: Set up code signing
        script: |
          cd src
          xcode-project use-profiles
      - name: Build iOS
        script: |
          cd src
          xcodebuild -workspace "Intake on-the-Go.xcworkspace" \
            -scheme "Intake on-the-Go" \
            -configuration Release \
            -archivePath build/Intake-on-the-Go.xcarchive \
            archive
    artifacts:
      - src/build/Intake-on-the-Go.xcarchive
