
workflows:
  ios-workflow:
    name: Intake on-the-Go iOS
    max_build_duration: 60
    integrations:
      app_store_connect: Codemagic
    environment:
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
    scripts:
      - name: Unzip project
        script: |
          unzip *.zip
      - name: Install CocoaPods
        script: |
          cd src
          pod install
      - name: Set up keychain
        script: keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files \
            org.aohministry.intakeonthego \
            --type IOS_APP_STORE \
            --create
      - name: Add certificates
        script: keychain add-certificates
      - name: Set up code signing
        script: |
          cd src
          xcode-project use-profiles
      - name: Build iOS
        script: |
          cd src
          xcodebuild -workspace "Intake on-the-Go.xcworkspace" \
            -scheme "Intake on-the-Go" \
            -configuration Release \
            -archivePath build/Intake-on-the-Go.xcarchive \
            archive
    artifacts:
      - src/build/Intake-on-the-Go.xcarchive
